"""Tests for the STROBE checklist generator.

The point of the generator is that it refuses to emit a false claim, so most
of what is tested here is the refusing. A checklist that renders whatever it
is given would be worse than no checklist at all: it would put a statement
about where each item is addressed in front of an editor, with the authority
of a completed form and none of the checking.
"""

import pandas as pd
import pytest


@pytest.fixture(name="strobe")
def _strobe(load_src_module):
    return load_src_module("43_strobe_checklist.py")


@pytest.fixture(name="rows")
def _rows():
    return pd.DataFrame(
        [
            {
                "item": "1a",
                "recommendation": "Indicate the design",
                "anchor": r"\section{Introduction}",
                "manuscript_text": "The abstract names the design.",
            },
            {
                "item": "12c",
                "recommendation": "Explain how missing data were addressed",
                "anchor": r"\section{Introduction}|\section{Results}",
                "manuscript_text": "Coverage threshold; no imputation.",
            },
        ]
    )


MANUSCRIPT = (
    r"\section{Introduction}" + "\nbackground\n" + r"\section{Results}" + "\nnumbers\n"
)


def test_anchors_split_on_the_pipe_and_ignore_blanks(strobe):
    assert strobe.split_anchors("a|b") == ["a", "b"]
    assert strobe.split_anchors(" a || b ") == ["a", "b"]
    assert strobe.split_anchors("") == []


def test_sub_lettered_items_count_toward_their_number(strobe):
    assert strobe.item_number("12c") == "12"
    assert strobe.item_number("1a") == "1"
    assert strobe.item_number("22") == "22"


def test_latex_special_characters_are_escaped(strobe):
    escaped = strobe.escape_latex("100% & _cover_ #1 ~ ^ $x$ {y}")
    assert r"\%" in escaped and r"\&" in escaped and r"\_" in escaped
    assert r"\#" in escaped and r"\$" in escaped
    assert r"\textasciitilde{}" in escaped and r"\textasciicircum{}" in escaped
    assert r"\{" in escaped and r"\}" in escaped
    # A backslash must become a printable one, not start a new control sequence.
    assert strobe.escape_latex("a\\b") == r"a\textbackslash{}b"


def test_resolution_records_where_each_anchor_lands(strobe, rows):
    resolution = strobe.resolve_anchors(rows, MANUSCRIPT)
    assert list(resolution["item"]) == ["1a", "12c", "12c"]
    assert resolution["resolved"].all()
    # Offsets must be the real positions, or the deposited resolution is a
    # decoration rather than evidence that the lookup happened.
    assert resolution["character_offset"].iloc[0] == 0
    assert resolution["character_offset"].iloc[2] == MANUSCRIPT.index(
        r"\section{Results}"
    )


def test_an_anchor_the_manuscript_lost_stops_the_run(strobe, rows):
    rows.loc[0, "anchor"] = r"\section{A section that was renamed}"
    with pytest.raises(ValueError, match="does not contain"):
        strobe.resolve_anchors(rows, MANUSCRIPT)


def test_an_item_with_no_anchor_stops_the_run(strobe, rows):
    rows.loc[1, "anchor"] = "  "
    with pytest.raises(ValueError, match="names no anchor"):
        strobe.resolve_anchors(rows, MANUSCRIPT)


def test_a_missing_numbered_item_stops_the_run(strobe, rows):
    with pytest.raises(ValueError, match="absent from the checklist"):
        strobe.verify_items_complete(rows, ("1", "12", "22"))


def test_an_item_with_no_statement_stops_the_run(strobe, rows):
    rows.loc[0, "manuscript_text"] = "   "
    with pytest.raises(ValueError, match="no statement of where addressed"):
        strobe.verify_items_complete(rows, ("1", "12"))


def test_a_complete_checklist_passes(strobe, rows):
    assert strobe.verify_items_complete(rows, ("1", "12")) is None


def test_rendered_table_carries_every_row_and_closes(strobe, rows):
    table = strobe.render_table(rows)
    assert table.startswith("% Generated by src/43_strobe_checklist.py")
    assert r"\begin{longtable}" in table and r"\end{longtable}" in table
    assert r"\label{tab:supp_strobe}" in table
    for item in rows["item"]:
        assert f"{item} &" in table
    assert table.count(r"\\") >= len(rows)


def test_the_deposited_checklist_resolves_against_the_real_manuscript(strobe):
    """The fixtures above prove the mechanism; this proves the actual file."""
    checklist = pd.read_csv(strobe.CHECKLIST, dtype=str).fillna("")
    manuscript = strobe.MANUSCRIPT.read_text(encoding="utf-8")

    strobe.verify_items_complete(checklist, strobe.REQUIRED_ITEMS)
    resolution = strobe.resolve_anchors(checklist, manuscript)
    assert resolution["resolved"].all()
    assert len(resolution) >= len(checklist)

    # The rendered table on disk must be the one this checklist produces, or
    # the Supplement is carrying a stale checklist that still compiles.
    assert strobe.TABLE_OUT.read_text(encoding="utf-8") == strobe.render_table(checklist)

    deposited = pd.read_csv(strobe.RESOLUTION_OUT, dtype=str)
    assert len(deposited) == len(resolution)
