"""Render the STROBE checklist, and refuse to render one that is not true.

Science and Medicine in Football desk-rejects a manuscript that states it
follows a reporting guideline without following it. A checklist is therefore
not a formality to be filled in at submission: it is a claim about where each
item is addressed, and a claim that can be wrong.

So the checklist is generated rather than written. Each row names one or more
anchors -- literal strings that must occur in the manuscript -- and this module
resolves every one of them against the manuscript source before emitting the
table. An item that points at a section which has been renamed, merged or cut
stops the run instead of reaching an editor as a false statement.

The resolution is also deposited, so a reader can see that the checklist was
checked rather than asserted.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CHECKLIST = ROOT / "data" / "manual" / "strobe_checklist.csv"
MANUSCRIPT = ROOT / "manuscript" / "manuscript.tex"
TABLE_OUT = ROOT / "manuscript" / "strobe_checklist_table.tex"
RESOLUTION_OUT = (
    ROOT / "data" / "processed" / "results" / "jsams_strobe_checklist_resolution.csv"
)

#: The 22 numbered STROBE items. Sub-lettered rows (1a, 12c) collapse onto
#: their number, so the check is that no numbered item is missing entirely.
REQUIRED_ITEMS = tuple(str(n) for n in range(1, 23))

#: Characters that would otherwise be read as markup when checklist prose is
#: dropped into a LaTeX cell. The manuscript is compiled with pdflatex, so an
#: unescaped percent sign silently swallows the rest of the line.
#:
#: Applied character by character, never as successive replacements: a
#: replacement that emits braces would otherwise be escaped again by a later
#: rule, turning one backslash into visible markup.
LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def split_anchors(anchor_field: str) -> list[str]:
    """Split one checklist row's anchor field into individual anchors."""
    return [part.strip() for part in str(anchor_field).split("|") if part.strip()]


def item_number(item: str) -> str:
    """Reduce ``12c`` to ``12`` so sub-lettered rows count toward their item."""
    return "".join(ch for ch in str(item) if ch.isdigit())


def escape_latex(text: str) -> str:
    """Make one checklist cell safe to typeset."""
    return "".join(LATEX_ESCAPES.get(char, char) for char in str(text))


def resolve_anchors(checklist: pd.DataFrame, manuscript: str) -> pd.DataFrame:
    """Locate every anchor in the manuscript, recording where each one lands.

    Position is recorded as well as presence: it is what lets a reader confirm
    that an item said to be addressed in the Discussion is not in fact anchored
    to a phrase in the Methods.
    """
    rows = []
    for _, row in checklist.iterrows():
        anchors = split_anchors(row["anchor"])
        if not anchors:
            raise ValueError(f"STROBE item {row['item']} names no anchor")
        for anchor in anchors:
            position = manuscript.find(anchor)
            if position < 0:
                raise ValueError(
                    f"STROBE item {row['item']} points at text the manuscript does "
                    f"not contain: {anchor!r}"
                )
            rows.append(
                {
                    "item": str(row["item"]),
                    "anchor": anchor,
                    "character_offset": position,
                    "resolved": True,
                }
            )
    return pd.DataFrame(rows)


def verify_items_complete(checklist: pd.DataFrame, required: Sequence[str]) -> None:
    """Refuse a checklist that silently omits a numbered item."""
    present = {item_number(item) for item in checklist["item"]}
    missing = [item for item in required if item not in present]
    if missing:
        raise ValueError(f"STROBE items absent from the checklist: {missing}")

    empty = [
        str(row["item"])
        for _, row in checklist.iterrows()
        if not str(row["manuscript_text"]).strip()
    ]
    if empty:
        raise ValueError(f"STROBE items with no statement of where addressed: {empty}")


def render_table(checklist: pd.DataFrame) -> str:
    """Build the checklist as a longtable the Supplement can input."""
    lines = [
        "% Generated by src/43_strobe_checklist.py. Do not edit by hand: every",
        "% anchor here was resolved against manuscript.tex when this was written,",
        "% and editing the table breaks that guarantee silently.",
        r"\begingroup",
        r"\footnotesize",
        # \LTleft and \LTright are deliberately left at their defaults. Pinning
        # both to 0pt removes the glue longtable uses to place the caption row
        # and overfills it by a full text width.
        r"\setlength{\LTcapwidth}{\textwidth}",
        r"\begin{longtable}{@{}p{0.05\textwidth}p{0.30\textwidth}p{0.57\textwidth}@{}}",
        r"\caption{STROBE checklist for cohort studies, completed for this "
        r"manuscript. Each item names the location in the manuscript that "
        r"addresses it; the locations are resolved against the manuscript source "
        r"by \texttt{src/43\_strobe\_checklist.py}, which fails rather than emit "
        r"an item pointing at text that is not there.}"
        r"\label{tab:supp_strobe}\\",
        r"\toprule",
        r"Item & Recommendation & Where addressed \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Item & Recommendation & Where addressed \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for _, row in checklist.iterrows():
        lines.append(
            f"{escape_latex(row['item'])} & {escape_latex(row['recommendation'])} & "
            f"{escape_latex(row['manuscript_text'])} \\\\"
        )
        lines.append(r"\addlinespace[2pt]")
    lines.extend([r"\end{longtable}", r"\endgroup", ""])
    return "\n".join(lines)


def main() -> None:  # pragma: no cover
    checklist = pd.read_csv(CHECKLIST, dtype=str).fillna("")
    manuscript = MANUSCRIPT.read_text(encoding="utf-8")

    verify_items_complete(checklist, REQUIRED_ITEMS)
    resolution = resolve_anchors(checklist, manuscript)

    RESOLUTION_OUT.parent.mkdir(parents=True, exist_ok=True)
    resolution.to_csv(RESOLUTION_OUT, index=False)
    TABLE_OUT.write_text(render_table(checklist), encoding="utf-8")

    print(f"Resolved {len(resolution)} anchors across {len(checklist)} checklist rows.")
    print(f"Wrote {TABLE_OUT.relative_to(ROOT)}")
    print(f"Wrote {RESOLUTION_OUT.relative_to(ROOT)}")


if __name__ == "__main__":  # pragma: no cover
    main()
